- hosts: localhost
  connection: local
  become: no
  roles:
    - role: homebrew
      tags: homebrew
    - role: ruby
      tags: ruby
    - role: dotfiles
      tags: dotfiles
  vars:
    # Tap external Homebrew repositories.
    #
    # e.g.
    # - homebrew/binary
    homebrew_repositories:
      - homebrew/dupes
    # Managed Homebrew packages.
    #
    # e.g.
    # - package_name
    # or
    # { name: package_name, state: package_state, install_options: [with-baz, enable-debug] }
    #
    # state choices: [head, latest, present, absent, linked, unlinked] (default latest)
    # install_options: string or sequence (default none)
    homebrew_packages:
      - readline # to use multibytes charactor on pry
      - openssl # to connect over https
      - imagemagick
      - apple-gcc42 # to build ruby 1.8.7-p371
    ruby_versions:
      - 2.3.0
