---
- shell: brew update
  register: result
  ignore_errors: yes
- get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/master/install
    dest: /tmp/brew_install
  when: result|failed
- shell: ruby /tmp/brew_install
  when: result|failed
- file:
    dest: /tmp/brew_install
    state: absent
- homebrew_tap:
    tap: '{{ item }}'
  with_items: homebrew_repositories
  when: homebrew_repositories
- homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('latest') }}"
    install_options: >
      {{
        item.install_options | default() | join(',')
        if item.install_options is not string
        else item.install_options
      }}
  with_items: homebrew_packages
  when: homebrew_packages
