---
- shell: bash -lc 'rbenv install {{ item }}'
  args:
    creates: /usr/local/anyenv/envs/rbenv/versions/{{ item }}
  with_items: ruby_versions
  notify: rehash rbenv
- shell: bash -lc 'gem install bundler --no-ri --no-rdoc'
  args:
    creates: /usr/local/anyenv/envs/rbenv/versions/{{ item }}/bin/bundle
  environment:
    RBENV_VERSION: '{{ item }}'
  with_items: ruby_versions
  notify: rehash rbenv
